### ISSUE TITLE
for every error in pool.query an unhandeld rejection with the same error is produced

### ISSUE THREAD

**Issue by volkmarbuehringer** [brianc/node-pg-pool#32]
.then(() => pool.query(`insert into weblog
( start, ende, url , message ,lenf )
          values($1,$2,$3,$4,$5 )`, [obj.start, obj.ende, obj.url, obj.message || "",obj.len]))
        .then(() => obj);

{"pid":12008,"hostname":"localhost.localdomain","level":50,"time":1477812965529,"msg":"Unhandled Rejection at: Promise {}","type":"Error","stack":"Error: pool is draining and cannot accept work\n    at Pool.acquire (/home/walter/projekt/tpg/node_modules/generic-pool/lib/generic-pool.js:385:11)\n    at module.exports.<anonymous> (/home/walter/projekt/tpg/node_modules/pg-pool/index.js:58:15)\n    at module.exports.Pool.connect (/home/walter/projekt/tpg/node_modules/pg-pool/index.js:56:10)\n    at module.exports.<anonymous> (/home/walter/projekt/tpg/node_modules/pg-pool/index.js:99:10)\n    at module.exports.Pool.query (/home/walter/projekt/tpg/node_modules/pg-pool/index.js:98:10)\n    at Promise.resolve.then.then (/home/walter/projekt/tpg/tester15.js:190:26)\n    at process._tickCallback (internal/process/next_tick.js:103:7)","v":1}

**Comment by charmander** [comment]
It’s difficult to tell because of the formatting, but it doesn’t seem as if you’re handling rejections in that snippet at all.
